services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}

      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}

    volumes:
      - ./wordpress:/var/www/html
      - ./php:/config
      - ./docker/entrypoint.sh:/entrypoint.sh

    entrypoint: ["/entrypoint.sh"]

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
